<?php

namespace royaltransfer\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends EntityRepository
{
    /**
     * Find all tours
     * @return array
     */
    public function findAllTours()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT t FROM CoreBundle:tour t ORDER BY t.created DESC')
                    ->getResult();
    }

}
